### ISSUE TITLE
Define the Editor Style Using Styled Components

### ISSUE THREAD

**Issue by Xxy1016** [paion-data/nexusgraph#47]
We want to use the Styled Components to define the styles of the Editor and its plug-ins, but some styles of Styled Components are not working, such as `ContentEditable`，we defined `InputContainer` to wrap it, but the `outline` attribute didn't work and had to be temporarily written as an inline style to get the desired effect.
```
<InputContainer>
   <ContentEditable style={{ outline: 0 }} className="editor-input" />
 </InputContainer>
```

**Comment by QubitPi** [comment]
We shall first search Lexical community to see if somebody else has the same or similar issue and how the community respond to it
